import sharp from 'sharp'
import { writeFileSync } from 'node:fs'
import { loadMask, marchingSquares, contourArea, simplifyClosed, smoothClosedPath } from './trace.mjs'

const REGION = { left: 150, top: 320, width: 280, height: 260 }
const SRC = 'public/CLOSEEYELOGO.PNG.jpeg'

const mask = await loadMask(SRC, { ...REGION, threshold: 0.22 })
const contours = marchingSquares(mask)
const ranked = contours
  .map((pts) => ({ pts, area: contourArea(pts) }))
  .sort((a, b) => b.area - a.area)

const [lobesOuter, lobesInner, ringOuter, plus, ringInner] = ranked.map((c) => c.pts)

const EPS = 1.6
const simp = {
  lobesOuter: simplifyClosed(lobesOuter, EPS),
  lobesInner: simplifyClosed(lobesInner, EPS),
  ringOuter: simplifyClosed(ringOuter, EPS * 1.2),
  plus: simplifyClosed(plus, EPS),
  ringInner: simplifyClosed(ringInner, EPS * 1.2),
}
for (const [k, v] of Object.entries(simp)) console.log(k, 'points:', v.length)

const paths = {
  lobesOuter: smoothClosedPath(simp.lobesOuter),
  lobesInner: smoothClosedPath(simp.lobesInner),
  ringOuter: smoothClosedPath(simp.ringOuter),
  plus: smoothClosedPath(simp.plus),
  ringInner: smoothClosedPath(simp.ringInner),
}

// Canonical CloseEye brand gradient/accent, already defined in index.html's
// inline splash SVG (#logoGrad) — keep these exact values per the user's
// "keep the original CloseEye green gradient" requirement.
const topColor = '#a8ff3e'
const bottomColor = '#1a6b3a'
const accentColor = '#4ade80'

const W = REGION.width, H = REGION.height
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <defs>
    <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="${topColor}"/>
      <stop offset="100%" stop-color="${bottomColor}"/>
    </linearGradient>
  </defs>
  <path d="${paths.lobesOuter} ${paths.lobesInner}" fill="url(#g)" fill-rule="evenodd"/>
  <path d="${paths.plus}" fill="${accentColor}"/>
  <path d="${paths.ringOuter} ${paths.ringInner}" fill="${accentColor}" fill-rule="evenodd"/>
</svg>`

writeFileSync('public/_traced.svg', svg)
await sharp(Buffer.from(svg)).resize(W * 3, H * 3).png().toFile('public/_traced.png')
console.log('wrote public/_traced.svg, public/_traced.png')

// Tightly-cropped, square, icon-ready viewBox: bbox of all shapes + ~12% pad,
// centered. This is just a re-framing of the same paths (no shape changes) so
// the mark fills more of the canvas at small icon sizes.
const allPts = [...simp.lobesOuter, ...simp.ringOuter, ...simp.plus]
const xs = allPts.map((p) => p[0])
const ys = allPts.map((p) => p[1])
const bbox = { minX: Math.min(...xs), maxX: Math.max(...xs), minY: Math.min(...ys), maxY: Math.max(...ys) }
const bw = bbox.maxX - bbox.minX
const bh = bbox.maxY - bbox.minY
const cx = (bbox.minX + bbox.maxX) / 2
const cy = (bbox.minY + bbox.maxY) / 2
const size = Math.max(bw, bh) * 1.12
const vx = (cx - size / 2).toFixed(2)
const vy = (cy - size / 2).toFixed(2)
const vsize = size.toFixed(2)

const iconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vx} ${vy} ${vsize} ${vsize}">
  <defs>
    <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="${topColor}"/>
      <stop offset="100%" stop-color="${bottomColor}"/>
    </linearGradient>
  </defs>
  <path d="${paths.lobesOuter} ${paths.lobesInner}" fill="url(#g)" fill-rule="evenodd"/>
  <path d="${paths.plus}" fill="${accentColor}"/>
  <path d="${paths.ringOuter} ${paths.ringInner}" fill="${accentColor}" fill-rule="evenodd"/>
</svg>`
writeFileSync('public/_traced_icon.svg', iconSvg)
console.log('icon viewBox:', vx, vy, vsize, vsize)

// Furthest distance from the bbox center to any traced point — used to size
// the mark for maskable icons (W3C safe zone = central 80%-diameter circle).
const maxRadius = Math.max(...allPts.map((p) => Math.hypot(p[0] - cx, p[1] - cy)))
console.log('max radius from center:', maxRadius.toFixed(2))

// Emit the traced path data + viewBox + brand colors as a small JS module so
// scripts/icons/mark.mjs can build favicon/app-icon/splash variants without
// re-running contour extraction.
const moduleSrc = `// AUTO-GENERATED by scripts/icons/extract2.mjs — do not hand-edit.
// Pixel-traced from public/CLOSEEYELOGO.PNG.jpeg (marching squares +
// Douglas-Peucker simplify + Catmull-Rom smoothing). Regenerate by running
// extract2.mjs again if the source logo changes.

export const VIEWBOX = { x: ${vx}, y: ${vy}, size: ${vsize} }
export const MAX_RADIUS = ${maxRadius.toFixed(2)}
export const RIBBON_D = "${paths.lobesOuter} ${paths.lobesInner}"
export const PLUS_D = "${paths.plus}"
export const RING_D = "${paths.ringOuter} ${paths.ringInner}"
export const GRADIENT_FROM = "${topColor}"
export const GRADIENT_TO = "${bottomColor}"
export const ACCENT = "${accentColor}"
`
writeFileSync('scripts/icons/traced-paths.mjs', moduleSrc)
console.log('wrote scripts/icons/traced-paths.mjs')

// side-by-side with original
const orig = await sharp(SRC).extract(REGION).resize(W * 3, H * 3, { kernel: 'lanczos3' }).png().toBuffer()
const traced = await sharp('public/_traced.png').toBuffer()
await sharp({ create: { width: W * 6 + 20, height: H * 3, channels: 4, background: '#000000' } })
  .composite([
    { input: orig, left: 0, top: 0 },
    { input: traced, left: W * 3 + 20, top: 0 },
  ])
  .png()
  .toFile('public/_side_by_side.png')
console.log('wrote public/_side_by_side.png')
